openapi: 3.0.0
info:
  title: Essote Palaute REST API
  description: REST API for Essote Palaute
  version: "1.0"
paths:
  /v1/system/ping:
    get:
      operationId: ping
      summary: Replies with pong
      description: Replies ping with pong
      tags:
        - System
      responses:
        "200":
          description: Pong
          content:
            text/plain:
              schema:
                type: string
  /v1/reviewProducts:
    get:
      operationId: listReviewProducts
      summary: Lists reviewProducts
      tags:
        - ReviewProducts
      responses:
        "200":
          description: Returns a list of reviewProducts
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ReviewProduct"
        "default":
          description: Invalid request was sent to the server
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/Error"
  /v1/reviewProducts/{reviewProductId}:
    get:
      operationId: findReviewProduct
      summary: Finds reviewProduct
      description: Finds single reviewProduct
      parameters:
        - name: reviewProductId
          in: path
          description: reviewProduct id
          required: true
          schema:
            type: integer
            format: int32
      tags:
        - ReviewProducts
      responses:
        "200":
          description: Returns a single reviewProduct
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/ReviewProduct"
        "default":
          description: Invalid request was sent to the server
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/Error"
  /v1/reviews:
    get:
      operationId: listReviews
      summary: Lists reviews
      parameters:
        - name: productId
          in: query
          description: product id
          required: false
          schema:
            type: integer
            format: int32
        - name: minRating
          in: query
          description: min rating
          required: false
          schema:
            type: integer
            format: int32
        - name: maxRating
          in: query
          description: max rating
          required: false
          schema:
            type: integer
            format: int32
        - name: minReviewLength
          in: query
          description: displays only reviews containing at least given amount of characters
          required: false
          schema:
            type: integer
            format: int32
        - name: firstResult
          in: query
          description: First result
          required: false
          schema:
            type: integer
            format: int32
        - name: maxResults
          in: query
          description: Max results
          required: false
          schema:
            type: integer
            format: int32
        - name: sort
          in: query
          description: Sort
          required: false
          schema:
            $ref: '#/components/schemas/ReviewListSort'
      description: |
        Lists reviews
      tags:
        - Reviews
      responses:
        "200":
          description: Returns a list of reviews
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Review"
        "default":
          description: Invalid request was sent to the server
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/Error"
  /v1/surveys:
    get:
      operationId: listSurveys
      summary: Lists surveys
      description: |
        Lists surveys
      tags:
        - Surveys
      responses:
        "200":
          description: Returns a list of surveys
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Survey"
        "default":
          description: Invalid request was sent to the server
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/Error"
  /v1/surveys/{surveyName}:
    get:
      operationId: findSurvey
      summary: Finds survey
      description: |
        Finds single survey
      parameters:
        - name: surveyName
          in: path
          description: survey name
          required: true
          schema:
            type: string 
      tags:
        - Surveys
      responses:
        "200":
          description: Returns a single survey
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/Survey"
        "default":
          description: Invalid request was sent to the server
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/Error"
  /v1/surveys/{surveyName}/questions:
    get:
      operationId: listSurveyQuestions
      summary: lists questions of survey
      description: |
        Lists questions of sigle survey
      parameters:
        - name: surveyName
          in: path
          description: survey name
          required: true
          schema:
            type: string 
      tags:
        - Surveys
      responses:
        "200":
          description: Returns a single survey
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SurveyQuestion"
        "default":
          description: Invalid request was sent to the server
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/Error"
  /v1/surveys/{surveyName}/questions/{questionNumber}/summary:
    get:
      operationId: findSurveyQuestionSummary
      summary: Finds survey question summary
      description: |
        Finds single survey question summary
      parameters:
        - name: surveyName
          in: path
          description: survey name
          required: true
          schema:
            type: string
        - name: questionNumber
          in: path
          description: Question number
          required: true
          schema:
            type: integer
            format: int32
      tags:
        - Surveys
      responses:
        "200":
          description: Returns a single survey
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/SurveyQuestionSummary"
        "default":
          description: Invalid request was sent to the server
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Review:
      properties:
        id:
          type: integer
          format: int32
        productId:
          type: integer
          format: int32
        rating:
          type: integer
          format: int32
        created:
          type: string
          format: date-time
          description: Create time.
        modified:
          type: string
          format: date-time
          description: Create time.
        review:
          type: string
        location:
          type: string
    SurveyQuestion:
      properties:
        number:
          type: integer
          format: int32
        question:
          type: string
    Survey:
      properties:
        name:
          type: string
        questions:
          type: array
          items:
            $ref: "#/components/schemas/SurveyQuestion"
    SurveyQuestionSummary:
      properties:
        positive:
          type: integer
          format: int32
        negative:
          type: integer
          format: int32
        total:
          type: integer
          format: int32
    ReviewListSort:
      type: string
      enum:
        - CREATED_DESC
        - CREATED_ASC
    ReviewProduct:
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        displayName:
          type: string
        link:
          type: string
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string